[package]
name = "redox_uefi_alloc"
version = "0.1.14"
edition = "2021"
description = "UEFI allocation support"
license = "MIT"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
repository = "https://gitlab.redox-os.org/redox-os/uefi"

[lib]
name = "uefi_alloc"

[dependencies]
redox_uefi = { path = "../uefi" , version = "0.1.14" }
